dl_sites:
  - "1Fichier"
  - "FreeDL"
  - "GoFile"
  - "MegaUp"

dl_names:
  Base Game:
    - "Base Game"
  Update:
    - "Update"
  DLC:
    - "DLC"

forbidden_titles:
  - "Latest RAW Game Updates [17th April 2024][47 New Updates] [DISCONTINUED]"

regions:
  USA: "USA|UAS"
  Europe: "EUR"
  Japan: "JP|JPN|JAPAN"
  Asia: "ASIA"
  Korea: "KOR"
  Taiwan: "TWN"
  Hong Kong: "HKG"
  Chinese Taiwan: "CHT"

languages:
  English: "En(?:-[A-Z][A-Z])?"
  Afrikaans: "Af"
  Albanian: "Sq"
  Arabic: "Ar"
  Basque: "Eu"
  Bulgarian: "Bg"
  Catalan: "Ca"
  Chinese (Simplified): "Zh-Hans|Zh"
  Chinese (Traditional): "Zh-Hant|Zh"
  Cornish: "Kw"
  Croatian: "Hr"
  Czech: "Cs"
  Danish: "Da"
  Dutch: "Nl"
  Estonian: "Et"
  Finnish: "Fi"
  French: "Fr(?!-CA)(?:-[A-Z][A-Z])?"
  French (Canadian): "Fr-CA"
  Gaelic: "Gd"
  German: "De"
  Greek: "El"
  Hebrew: "He"
  Hindi: "Hi"
  Hungarian: "Hu"
  Icelandic: "Is"
  Indonesian: "Id"
  Italian: "It"
  Japanese: "Ja"
  Korean: "Ko"
  Latvian: "Lv"
  Lithuanian: "Lt"
  Macedonian: "Mk"
  Norwegian: "No"
  Polish: "Pl"
  Portuguese: "Pt(?!-BR)(?:-[A-Z][A-Z])?"
  Portuguese (Brazilian): "Pt-BR"
  Punjabi: "Pa"
  Romanian: "Ro"
  Russian: "Ru"
  Serbian: "Sr"
  Slovak: "Sk"
  Slovenian: "Sl"
  Spanish: "Es(?!-(MX|XL))(?:-[A-Z][A-Z])?"
  Spanish (Latin American): "Es-XL"
  Spanish (Mexican): "Es-MX"
  Swedish: "Sv"
  Tamil: "Ta"
  Thai: "Th"
  Turkish: "Tr"
  Ukranian: "Uk"