name: Publish

on: [push, pull_request]

jobs:
  build_sdist_and_wheel:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"
      - name: Install build
        run: python -m pip install build
      - name: Build sdist
        run: python -m build --sdist --wheel --outdir dist/ .
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-source
          path: dist/*

  build_and_upload_executable:
    name: Build and upload executable
    runs-on: windows-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -e .
      - name: Build package
        run: >
          pyinstaller nxbrew_dl_gui.py 
          --copy-metadata nxbrew_dl 
          --collect-data nxbrew_dl
          --onefile 
          -n nxbrew_dl.exe
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
